@baseURL = https://localhost:8000/api

### GET all employees
GET {{baseURL}}/employees

### GET an employee by ID
GET {{baseURL}}/employees/john-doe

### GET an employee by ID with tickets
GET {{baseURL}}/employees/john-doe/tickets

### GET an employee with INVALID ID
GET {{baseURL}}/employees/INVALID_ID

### POST a new employee
POST {{baseURL}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "managerId": "MGR001",
    "designation": "Software Engineer",
    "department": "IT",
    "gender": "MALE",
    "dateOfBirth": "1990-05-15",
    "dateOfJoining": "2020-03-01",
    "salary": 75000,
    "email": "john.doe@example.com",
    "phoneNo": "1234567890",
    "password": "securePassword123"
}




### POST a new Different Employee
POST {{baseURL}}/employees
Content-Type: application/json

{
    "name": "Jane Smith",
    "managerId": "MGR002",
    "designation": "HR Manager",
    "department": "Human Resources",
    "gender": "FEMALE",
    "dateOfBirth": "1985-10-25",
    "dateOfJoining": "2018-07-10",
    "salary": 85000,
    "email": "jane.smith@example.com",
    "phoneNo": "0987654321",
    "password": "strongPassword456"
  }


### Delete the employee by ID
DELETE {{baseURL}}/employees/john-doe

### PUT to update the employee Details
PUT {{baseURL}}/employees/EMP001
Content-Type: application/json

{
    "EMPLOYEE_TAKEHOME": 60000
}
